### ISSUE TITLE
Stuck on setup: deprecation issues?

### ISSUE THREAD

**Issue by buckethat** [yhagio/kickstarter-clone#1]
I run `npm start` and get this error:

```
> kickstarterclone@1.0.0 start /vagrant
> node build/index.js

module.js:327
    throw err;
    ^

Error: Cannot find module '/vagrant/build/index.js'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

npm ERR! Linux 3.13.0-96-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.4.2
npm ERR! npm  v3.8.5
npm ERR! code ELIFECYCLE
npm ERR! kickstarterclone@1.0.0 start: `node build/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the kickstarterclone@1.0.0 start script 'node build/index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the kickstarterclone package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build/index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs kickstarterclone
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls kickstarterclone
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /vagrant/npm-debug.log
```

I've looked online but the only suggestions is to upgrade node. I appreciate any help you can give me. Thanks in advance!

**Comment by buckethat** [comment]
@yhagio any chance you could look at this? would really appreciate it. thanks

**Comment by yhagio** [comment]
I'm sorry, but I'm not sure.
Since this was just experiment, so I don't recommend using it, but as an example.
Also many dependencies are old or deprecated.

**Comment by buckethat** [comment]
ok thanks for the reply! I'll keep trying and let you know if I can solve it
